[package]
name = "minecraft_cubes"
version = "0.1.0"
edition = "2021"

[dependencies]
minifb = "0.19"               
nalgebra-glm = "0.2.0"         
image = "0.23"                 
rand = "0.8"
rayon = "1.5"             
rodio = "0.13"    